### PR TITLE
Czech number support

### PR DESCRIPTION
**Pull request by sime**
Attempt of #249

### CODE REVIEW

**Comment by sime** [comment]
I have added a new test, though I don't know how to get it to pass, nor do I really understand what split() does.

**Comment by floere** [comment]
Split is described in the DSL:
https://github.com/floere/phony/blob/master/lib/phony/dsl.rb#L169-L183

Since `+420123456789` falls back to a `fixed(3)` NDC (the `123` part), whose local part is then `split(3,3)` (so, `456 789`), it is a plausible number.

It would be a great idea if you just used the number that was "plausible" for the test :)

Does that help?

**Comment by floere** [comment]
Otherwise looks great!

**Comment by floere** [comment]
Hi @sime – the extensions to the Czech ruleset looks great, but unfortunately the test fails. Would you mind making it pass so I can include the PR in Phony? Cheers :)

**Comment by sime** [comment]
I haven't hit this problem since and have kind of lost interest to be honest.

**Comment by floere** [comment]
That's fine. Do you mind letting me know where the NDCs are from that are in the PR?

**Comment by sime** [comment]
I think you are after this. https://github.com/floere/phony/issues/249#issuecomment-98971671

**Comment by floere** [comment]
Thanks!

**Pull request closed without merging**
