### PR TITLE
Add special file for Saudi Arabia

### PR DESCRIPTION
**Pull request by gerardc**
Added some extra rules and documentation for Saudi Arabia.

### CODE REVIEW

**Comment by floere** [comment]
Very nice and clean PR, @gerardc! :+1: Thanks so much! Released in 2.15.14 :rocket:

**Comment by gerardc** [comment]
No problem, thank you for supporting the gem! :)

**Comment by floere** [comment]
My pleasure!

**Comment by gerardc** [comment]
@floere thanks again for merging, are you planning to release 2.15.14 soon?

**Comment by floere** [comment]
@gerardc Oops, my bad. The release process did not finish, and I optimistically assumed it had. Sorry! It is now released.

**Comment by floere** [comment]
@gerardc Thanks for pinging me!

**Comment by gerardc** [comment]
@floere awesome, thanks a lot!

**Pull request merged**
