### PR TITLE
Add some Japanese NDC pattern rules

### PR DESCRIPTION
**Pull request by miyucy**
Almost taken from [libphonenumber](https://github.com/google/libphonenumber/tree/master/resources/metadata/81) metadata.

### CODE REVIEW

**Comment by floere** [comment]
@miyucy Looking good! I'll review when you mark it as ready :)

**Comment by miyucy** [comment]
Thank you! 
I'm considering that metadata license. If it cannot re-use other product, I have to re-implement those regex. (I'm remember libmagic and activestorage problem)

**Comment by miyucy** [comment]
I thought the metadata was provided under the [same license](https://github.com/google/libphonenumber/blob/master/LICENSE) as the libphonenumber. 
Therefore, I think there is no problem to modification and re-distribution.

**Comment by floere** [comment]
@miyucy Thanks so much for your PR and work! 😊 Released in 2.19.13 🚀

**Comment by miyucy** [comment]
Thank you for release!

**Pull request merged**
