### PR TITLE
Update croatia zambia phone formats

### PR DESCRIPTION
**Pull request by saner**
This pull request updates mobile, landline and special phone number formats for Croatia and Zambia , it is based on the information from
https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml

### CODE REVIEW

**Comment by ronin** [comment]
@floere Is there a chance to merge it this week?

**Comment by ronin** [comment]
@floere Ping

**Comment by floere** [comment]
@saner @ronin Croatia fails on `Phony.refute.plausible?('+385 91 123456') # Too short` and `Phony.refute.plausible?('+385 21 1234567') # Too long`. Any ideas?

**Comment by floere** [comment]
@saner @ronin For now I've adapted the plausibility specs for Croatia to the definition. Please let me know if they are correct.

**Comment by floere** [comment]
Thanks so much, @saner! 😊 Released in 2.15.45 🚀

**Comment by saner** [comment]
Thanks @floere!

**Pull request merged**
