### PR TITLE
Add 1800, 1300 and 13 numbers for Australia

### PR DESCRIPTION
**Pull request by bethesque**
Thanks for your work. I have added some missing number formats for Australia.

### CODE REVIEW

**Comment by floere** [comment]
Thanks Beth – this is great! :+1: :tada: Released in 2.15.6 :rocket:

**Comment by bethesque** [comment]
Thanks for your quick response! We'll be able to upgrade and remove our dirty hack ;)

**Comment by floere** [comment]
Glad to hear it :smile: Of course, providers of nice QED/RSpec tests and clean code always get preferred treatment!

**Comment by bethesque** [comment]
:+1:

**Pull request merged**
