### PR TITLE
Issue 17: recognize and update format for Bulgarian numbers

### PR DESCRIPTION
**Pull request by davidkovsky**
I based this off of http://www.wtng.info/wtng-359-bg.html. I'm open to ideas for improvement. This arose from the need to recognize a specific number for Sofia, Bulgaria as valid.

### CODE REVIEW

**Comment by floere** [comment]
@davidkovsky Apologies for the late answer, I was holidaying 😅 This looks great, thanks so much!

The only improvement that I can see right now would be to combine some regexes, e.g. `match(/^(31)\d{6}$/) >> split(6) |` and `match(/^(32)\d{6}$/) >> split(6) |` into `match(/^(31|32)\d{6}$/) >> split(6) |`. But otherwise it looks good, loving the many/exhaustive specs 👍 

I've already pulled in a smaller PR that improved Sofia, see https://github.com/floere/phony/pull/407, by @SofiaMargariti. I noticed that the local number part is split differently in the sources (`+359 2 1234567` vs. `+359 2 123 4567`). This PR opts to not split (as described in http://www.wtng.info/wtng-359-bg.html), while the other PR does (as described in 
https://en.wikipedia.org/wiki/Telephone_numbers_in_Bulgaria). I do tend to prefer rules that do a split for readability.
It's not a big issue, but perhaps any of you has an opinion/data on it? Thanks in advance 😊

**Comment by floere** [comment]
Other than the regexp issue and local number splitting… very happy to pull! 🚀

**Comment by davidkovsky** [comment]
Thanks for the feedback. I'm happy to combine regexes. I was trying to keep it easy to compare lines in the spec with lines in the code. I think my original thought was along the lines of `match(/3^(1|2)\d{6}$/) >> split(6) |`, which would have been harder to compare with the spec than your suggestion of `match(/^(31|32)\d{6}$/) >> split(6) |`.

I think consistency is the most important thing for the split rules so I'm happy to follow your preference. I'll try to prepare an update soon.

**Comment by davidkovsky** [comment]
@floere I pushed to new branch of my repository to keep the history clean. I'm going to close this PR and open a new one from that branch.

**Pull request closed without merging**
