### PR TITLE
Add support for UAE mobile format +971 58 XXX XXXX

### PR DESCRIPTION
**Pull request by ronin**
Here is another PR with new mobile prefix available in United Arab Emirates.

### CODE REVIEW

**Comment by ronin** [comment]
@floere Any plans on merging soon? :)

**Comment by floere** [comment]
@ronin Thanks, Michał! 😊 Much appreciated, also for reminding me! Released in 2.15.39 🚀

**Comment by ronin** [comment]
@floere Great, thanks!

**Comment by floere** [comment]
@ronin Thank _you_!

**Pull request merged**
