### PR TITLE
Add NDCS for Russian Tele2 & Yota operators.

### PR DESCRIPTION
**Pull request by estum**

### CODE REVIEW

**Comment by floere** [comment]
Thanks @estum! I currently only accept PRs with tests for new functionality – would you mind adding these? Let me know if you don't know where to start. Thanks 😊

**Comment by yurijmi** [comment]
@floere will you merge this if I'll make specs myself?

**Comment by floere** [comment]
@yurijmi Absolutely, if you add either qed and/or rspec tests.

**Comment by floere** [comment]
@yurijmi Still happy to merge with tests :)

**Comment by izzm** [comment]
Please add new Beeline NDCS 969 too.

**Comment by floere** [comment]
@izzm Feel free to add it too :) Let me know if you don't know how!
@yurijmi Do you think you'll have time to add some simple tests – or do you not know how?

**Comment by yurijmi** [comment]
@floere oh i'm sorry. Got busy and forgot about it :(
I'll try implementing tests this week

**Comment by floere** [comment]
@yurijmi Not a problem at all – let me know if you need pointers! :)

**Comment by floere** [comment]
@yurijmi Hi Yuri! Shall I close this for now? (It's fine if you don't get to it – but it would help me keep the project clean and in order to close remaining PRs)

**Comment by yurijmi** [comment]
Can you reopen it when I finally get to it? If so you can close it for now. Sorry, got busy again :(

**Comment by floere** [comment]
@yurijmi Hi Yuri – I'll leave it open for now, then 😊 (I may close it at a later date)

**Pull request closed without merging**
