### PR TITLE
Update latest Cambodian prefixes and rules.

### PR DESCRIPTION
**Pull request by dwilkie**
This PR provides better validation of Cambodian numbers based off the latest data.

http://www.khmerdigitalpost.com/national-numbering-plans-in-cambodia-by-2014/

### CODE REVIEW

**Comment by dwilkie** [comment]
@floere anything else needed for this PR?

**Comment by floere** [comment]
No, absolutely not – it's a beautiful PR. Thanks for pinging – somehow that one got past me, sorry about that.

**Comment by floere** [comment]
Released in 2.14.3.

**Comment by dwilkie** [comment]
No problem! Thanks for merging it in!

**Comment by floere** [comment]
👍

**Pull request merged**
