### PR TITLE
Update README.textile

### PR DESCRIPTION
**Pull request by onmyway133**
I think you mean "Australia" 😉

### CODE REVIEW

**Comment by floere** [comment]
@onmyway133 Oh thanks, and also not `number number` – so `Australian number` would be right. Do you feel like removing the second number and adding an n, too?

**Comment by onmyway133** [comment]
@floere sorry for the mess up. It should be right now 😄

**Comment by floere** [comment]
@onmyway133 Oh, don't be sorry! Many thanks for your work! 👏

**Comment by floere** [comment]
@onmyway133 Very thankful for any and all patches to be sent in 😄

**Comment by onmyway133** [comment]
@floere I wonder how we can make the data so generic that all programming languages can use

**Comment by floere** [comment]
@onmyway133 Have a look at https://github.com/googlei18n/libphonenumber for that :)

**Pull request merged**
