### PR TITLE
Fix Luxembourg phone numbers

### PR DESCRIPTION
**Pull request by bdewater**
A customer reported our application not accepting his phone number and when I saw #276 so I decided to complete the work started by @jdel :smile: 

I had to add a fallback match for the `it_splits '35227855', ['352', '27', '85', '5']` test case to pass. I'm no expert on Luxembourg numbers either but the changes to the existing tests don't seem too invasive.

### CODE REVIEW

**Comment by klaustopher** [comment]
Tested with the numbers that I had troubles with, and works like a charm :+1:

**Comment by floere** [comment]
What a nice PR. Thanks so much! :sunny: Also loving the collaboration going on here.

**Comment by floere** [comment]
Released as 2.15.17.

**Comment by jdel** [comment]
It took months, but it's finally tested and merged ! Thanks guys ! :thumbsup:

**Comment by floere** [comment]
@jdel Thank _you_! 😊

**Pull request merged**
