### PR TITLE
Add support for UAE mobile format +971 54 XXX XXXX

### PR DESCRIPTION
**Pull request by ronin**
This format was recently introduced in UAE.

### CODE REVIEW

**Comment by ronin** [comment]
@floere Is there a chance to merge this PR and release new version?

**Comment by floere** [comment]
@ronin Hi! I've added it to my calendar for tonight. Thanks for your patience 😊

**Comment by ronin** [comment]
@floere Cool, thanks :)

**Comment by floere** [comment]
@ronin Thanks Michał! 😊 🎉 Released in 2.15.28 🚀

**Pull request merged**
