### PR TITLE
Add 39 prefix to Brazil (MG)

### PR DESCRIPTION
**Pull request by rodrigorbltt**
The state of Minas Gerais (Brazil) also has the 39 prefix.

See [here](https://ddd.guiamais.com.br/busca/39)

### CODE REVIEW

**Comment by wagner** [comment]
This PR is invalid. NDC 39 does not exist.

**Comment by floere** [comment]
@wagner So is the information on the guiamais page incorrect? /cc @rodrigorbltt

**Comment by rodrigorbltt** [comment]
@floere Yes, I've looked on http://www.anatel.gov.br/institucional/ and there's no record of this code as a avaliable prefix.

**Comment by floere** [comment]
Thanks a lot, @wagner and @rodrigorbltt ! Boa tarde! 🌤

**Pull request closed without merging**
